import {test} from 'node:test';import assert from 'node:assert/strict';import {games} from '../src/catalog';import {createEngine,engines} from '../src/games';import {Snake,Stack} from '../src/games/arcade';import {Timing,Cut,Sokoban,Memory,Arithmetic} from '../src/games/mind';
// Canvas probe catches unsupported render paths in every engine without a browser.
const noop=()=>{};const context=new Proxy({measureText:(s:string)=>({width:s.length*9})},{get:(obj,key)=>key in obj?(obj as any)[key]:noop,set:()=>true}) as unknown as CanvasRenderingContext2D;
for(const g of games)test(`${g.name}: renders, advances, abandons and repeats deterministically`,()=>{assert.ok(engines[g.engine]);const a=createEngine(g,42),b=createEngine(g,42);for(let i=0;i<360;i++){a.tick(1/60);b.tick(1/60);if(i%30===0){a.draw(context);b.draw(context)}}assert.equal(a.score,b.score);assert.deepEqual(a.done,b.done);assert.ok(Number.isFinite(a.t));assert.ok(Number.isFinite(a.score));const repeat=createEngine(g,42);repeat.draw(context);assert.equal(repeat.t,0);repeat.finish('abandoned');assert.equal(repeat.done!.value,null);assert.equal(repeat.done!.status,'abandoned')});
test('snake grows, disallows reversal and ends on collision',()=>{const e=new Snake(games.find(g=>g.engine==='snake')!,3);e.food={x:9,y:10};e.tick(.23);assert.equal(e.body.length,4);assert.equal(e.score,1);e.key('left',true);assert.deepEqual(e.pending,{x:1,y:0});for(let i=0;i<20;i++)e.tick(.23);assert.equal(e.done?.status,'failed')});
test('precision records five centered hits and finishes once',()=>{const e=new Timing(games.find(g=>g.engine==='hawk')!,3);for(let i=0;i<5;i++)e.action('action',{x:0,y:0});assert.equal(e.done?.value,100);const old=e.done;e.finish('failed',0);assert.equal(e.done,old)});
test('cut uses true clipped area fractions',()=>{const e=new Cut(games.find(g=>g.engine==='cut')!,3);assert.equal(e.area({x:210,y:0},{x:210,y:560}),.5);assert.ok(Math.abs(e.area({x:85+250/3,y:0},{x:85+250/3,y:560})-1/3)<1e-8)});
test('Sokoban level is solvable, supports undo, then advances',()=>{const e=new Sokoban(games.find(g=>g.engine==='sokoban')!,2);e.action('right',{x:0,y:0});e.action('up',{x:0,y:0});e.action('undo',{x:0,y:0});assert.equal(e.box.y,3);e.action('up',{x:0,y:0});e.action('up',{x:0,y:0});assert.equal(e.level,2);assert.equal(e.score,10)});
test('stack trims overlap and loses on a non-overlapping block',()=>{const e=new Stack(games.find(g=>g.engine==='stack')!,3);e.x=250;e.action('action');assert.equal(e.width,220);e.x=0;e.action('action');assert.equal(e.done?.status,'failed')});
test('memory failure ends run and round success increases difficulty',()=>{const e=new Memory(games.find(g=>g.engine==='simon')!,3);e.phase='answer';for(const i of [...e.seq])e.action(['left','up','right','down'][i],{x:0,y:0});assert.equal(e.level,2);e.phase='answer';e.action(['left','up','right','down'][(e.seq[0]+1)%4],{x:0,y:0});assert.equal(e.done?.status,'failed')});
test('arithmetic errors add time and require correct response',()=>{const e=new Arithmetic(games.find(g=>g.engine==='math')!,3);e.submit(-1);assert.equal(e.penalty,2);assert.equal(e.round,0);for(let i=0;i<5;i++)e.submit(e.answer);assert.equal(e.done?.status,'completed');assert.equal(e.done?.value,2)});
test('dictation and pi preserve their earned points as time advances',()=>{for(const name of ['dictation','pi']){const e=new Arithmetic(games.find(g=>g.engine===name)!,2);e.action(name==='pi'?'1':e.digits[0],{x:0,y:0});const score=name==='pi'?1:e.score;e.tick(.1);if(name==='pi')assert.equal(e.score,score);assert.equal(e.hits,1)}});
test('phone excludes memorization from result but counts all time spent',()=>{const e=new Arithmetic(games.find(g=>g.engine==='phone')!,2);e.tick(4.1);assert.equal(e.t,0);assert.equal(e.elapsed,4.1);e.tick(1);for(const d of e.digits)e.action(d,{x:0,y:0});assert.equal(e.done!.value,1);assert.equal(e.elapsed,5.1)});
test('all games accept mixed touch and keyboard input without invalid scores',()=>{for(const g of games){const e=createEngine(g,92);for(let i=0;i<600&&!e.done;i++){e.tick(1/60);if(i%20===0){const k=['left','up','right','down','action','1','enter'][Math.floor(i/20)%7];e.key(k,true);e.key(k,false);e.input('down',{x:40+i%320,y:100+i%400});e.input('move',{x:80+i%250,y:120+i%300});e.input('up',{x:80+i%250,y:120+i%300})}e.draw(context)}assert.ok(Number.isFinite(e.score),g.name)}});
test('jumper responds to touch steering and helix separates rotation from descent',()=>{const jumper=createEngine(games.find(g=>g.engine==='jumper')!,4);const old=(jumper as any).x;jumper.input('down',{x:330,y:300});jumper.tick(.1);assert.ok((jumper as any).x>old);const helix=createEngine(games.find(g=>g.engine==='helix')!,4);helix.input('down',{x:200,y:100});helix.input('move',{x:300,y:100});helix.tick(.1);assert.equal((helix as any).depth,0);assert.equal(helix.done,null)});
