import {Engine,C,W,H,clamp,dist,text,rect,circle,line,animal,button,type Point} from './core';
export class Flyer extends Engine {
 x=140;y=280;vx=135;vy=0;obstacles:{x:number;y:number;w:number;h:number;passed:boolean}[]=[];spawn=0;side=0;spikesY=140;
 step(dt:number){const en=this.g.engine;const speed=125+this.t*2;
 if(en==='flappy'){this.vy+=620*dt;this.y+=this.vy*dt;if(this.t>this.spawn){this.spawn=this.t+1.8;const gap=this.rand(170,390);this.obstacles.push({x:440,y:gap,w:65,h:165,passed:false})}for(const o of this.obstacles){o.x-=speed*dt;if(Math.abs(o.x+32-this.x)<45&&(this.y<o.y-o.h/2+13||this.y>o.y+o.h/2-13))this.fail();if(!o.passed&&o.x+o.w<this.x){o.passed=true;this.score++;this.hits++}}}
 else if(en==='jet'){this.vy+=(this.held?-650:500)*dt;this.vy=clamp(this.vy,-170,170);this.y+=this.vy*dt;if(this.t>this.spawn){this.spawn=this.t+1.5;const gap=this.rand(100,310);this.obstacles.push({x:gap,y:-25,w:105,h:15,passed:false})}for(const o of this.obstacles){o.y+=speed*dt;if(Math.abs(o.y-this.y)<22&&(this.x<o.x-12||this.x>o.x+o.w+12))this.fail()}this.score=this.t*8;this.x=clamp(this.x+this.axis('x')*150*dt,35,385)}
 else if(en==='chicken'){this.vy+=320*dt;this.y+=this.vy*dt;this.x+=this.vx*dt+Math.sin(this.t*1.7)*25*dt;this.vx*=Math.pow(.15,dt);const half=Math.max(42,150-this.t*1.5);if(this.x<210-half+18||this.x>210+half-18)this.fail();if(this.y<160){this.score+=(160-this.y)/7;this.y=160}if(this.y>530)this.fail()}
 else if(en==='bat'||en==='gecko'){this.x+=this.vx*dt;this.vy+=en==='gecko'?350*dt:450*dt;this.y+=this.vy*dt;if(this.x<28||this.x>392){if(Math.abs(this.y-this.spikesY)<70)this.fail();this.x=clamp(this.x,28,392);this.vx=-this.vx;this.side=this.x<50?1:0;this.spikesY=this.rand(130,430);this.score+=en==='gecko'?3:1;this.hits++}if(en==='gecko'&&this.y<160){this.score+=(160-this.y)/15;this.y=160}}
 else if(en==='eel'){this.x+=this.vx*dt;this.score+=0;this.y=380;if(this.t>this.spawn){this.spawn=this.t+1.5;const gap=this.rand(65,285);this.obstacles.push({x:gap,y:-10,w:90,h:20,passed:false})}for(const o of this.obstacles){o.y+=speed*dt;if(Math.abs(o.y-this.y)<22&&(this.x<o.x||this.x>o.x+o.w))this.fail();if(!o.passed&&o.y>this.y){o.passed=true;this.score+=3;this.hits++}}}
 if(en!=='chicken'&&(this.y<20||this.y>540||this.x<12||this.x>408))this.fail();this.obstacles=this.obstacles.filter(o=>o.x>-100&&o.y<600);
 }
 action(k:string,p:Point){if(k==='move'&&this.held&&this.g.engine==='jet')this.x=clamp(p.x,25,395);if(!['tap','action','left','right'].includes(k))return;const en=this.g.engine;if(en==='flappy'||en==='bat')this.vy=-240;if(en==='gecko'){this.vx=this.x<210?160:-160;this.vy=-250}if(en==='chicken'){this.vy=-200;this.vx=(k==='left'||(k==='tap'&&p.x<210))?-130:130}if(en==='eel')this.vx=-this.vx;}
 draw(c:CanvasRenderingContext2D){this.background(c);const en=this.g.engine;
 if(en==='flappy')for(const o of this.obstacles){rect(c,o.x,0,o.w,o.y-o.h/2,C.green,0);rect(c,o.x,o.y+o.h/2,o.w,H-o.y,C.green,0)}
 if(en==='jet'||en==='eel')for(const o of this.obstacles){rect(c,0,o.y,o.x,14,en==='eel'?C.purple:C.red,2);rect(c,o.x+o.w,o.y,W-o.x-o.w,14,en==='eel'?C.purple:C.red,2);if(en==='eel')circle(c,o.x+o.w/2,o.y+40,7,C.yellow)}
 if(en==='chicken'){const half=Math.max(42,150-this.t*1.5);rect(c,0,0,210-half,H,'#91aa83',0);rect(c,210+half,0,210-half,H,'#91aa83',0);text(c,'←  Viento  →',210,60,14,C.muted)}
 if(en==='bat'||en==='gecko'){rect(c,0,0,12,H,C.ink,0);rect(c,408,0,12,H,C.ink,0);for(let i=-1;i<=1;i++){c.fillStyle=C.red;c.beginPath();const x=this.side===0?12:408;c.moveTo(x,this.spikesY+i*35-15);c.lineTo(x+(this.side===0?28:-28),this.spikesY+i*35);c.lineTo(x,this.spikesY+i*35+15);c.fill()}}
 animal(c,this.x,this.y,en==='eel'?C.purple:C.green,17);if(this.t<2)text(c,this.g.engine==='jet'?'Mantén para subir':'Toca para moverte',210,470,18,C.muted);
 }
}
export class Avoider extends Engine {
 x=210;y=440;lane=1;cars:{x:number;y:number;vx:number;size:number}[]=[];spawn=0;row=0;
 step(dt:number){const en=this.g.engine;this.x=clamp(this.x+this.axis('x')*220*dt,25,395);
 if(en==='asteroids'){this.y=clamp(this.y+this.axis('y')*220*dt,90,530);if(this.t>this.spawn){this.spawn=this.t+.7;this.cars.push({x:this.rand(25,395),y:-30,vx:this.rand(-25,25),size:this.rand(15,30)})}for(const o of this.cars){o.y+=(90+this.t*3)*dt;o.x+=o.vx*dt;if(dist(this,o)<o.size+16)this.fail()}this.score=Math.floor(this.t*2)}
 if(en==='traffic'){this.x=90+this.lane*120;if(this.t>this.spawn){this.spawn=this.t+Math.max(.4,1.15-this.t*.01);this.cars.push({x:90+this.int(0,2)*120,y:-80,vx:0,size:30})}for(const o of this.cars){o.y+=(150+this.t*5)*dt;if(Math.abs(o.x-this.x)<35&&Math.abs(o.y-this.y)<52)this.fail()}this.score=this.t*15}
 if(en==='crossing'){if(this.cars.length===0)for(let r=0;r<7;r++)for(let j=0;j<2;j++)this.cars.push({x:j*280+this.rand(0,100),y:480-r*55,vx:(r%2?1:-1)*this.rand(60,100),size:25});for(const o of this.cars){o.x+=o.vx*dt;if(o.x>480)o.x=-60;if(o.x<-60)o.x=480;if(Math.abs(this.x-o.x)<40&&Math.abs(this.y-o.y)<28)this.fail()}if(this.y<90){this.row+=8;this.y+=385;this.cars.forEach(o=>o.vx*=1.05)}this.score=Math.max(this.score,this.row+Math.round((535-this.y)/55))}
 this.cars=this.cars.filter(o=>en==='crossing'||o.y<650);
 }
 action(k:string,p:Point){const en=this.g.engine;if(en==='asteroids'&&this.held&&['tap','move'].includes(k)){this.x=clamp(p.x,25,395);this.y=clamp(p.y,90,530)}if(en==='traffic'){if(k==='left'||(k==='tap'&&p.x<210))this.lane=Math.max(0,this.lane-1);if(k==='right'||(k==='tap'&&p.x>=210))this.lane=Math.min(2,this.lane+1)}if(en==='crossing'){const d:Record<string,Point>={left:{x:-55,y:0},right:{x:55,y:0},up:{x:0,y:-55},down:{x:0,y:55}};if(k==='tap')k=p.y<this.y-20?'up':p.x<this.x?'left':'right';if(d[k]){this.x=clamp(this.x+d[k].x,30,390);this.y=clamp(this.y+d[k].y,45,535)}}}
 draw(c:CanvasRenderingContext2D){this.background(c);const en=this.g.engine;if(en==='traffic'){rect(c,35,0,350,H,'#d7ddcf',0);for(const x of [150,270])for(let y=-40;y<560;y+=70)rect(c,x,y+this.t*130%70,3,35,'#fff',0)}if(en==='crossing')for(let i=0;i<7;i++)rect(c,0,457-i*55,W,46,i%2?'#dde2d6':'#e6e9de',0);for(const o of this.cars)if(en==='asteroids'){circle(c,o.x,o.y,o.size,'#8c9c8a');circle(c,o.x-6,o.y-4,5,'#748672')}else{rect(c,o.x-28,o.y-20,56,40,C.red,7);rect(c,o.x-12,o.y-14,24,28,'#efc7ae',4)}animal(c,this.x,this.y,C.green,18)}
}
export class Needles extends Engine{
 angle=0;placed:number[]=[];projectile:number|null=null;wallShots:number[]=[];wallY=280;shots=0;
 step(dt:number){this.angle+=dt*(1.1+this.level*.25);if(this.projectile!==null){this.projectile-=650*dt;if(this.projectile<=360){const a=((Math.PI/2-this.angle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2);if(this.placed.some(v=>Math.abs(Math.atan2(Math.sin(v-a),Math.cos(v-a)))<.22)){this.fail();return}this.placed.push(a);this.projectile=null;this.score++;this.hits++;if(this.placed.length===8){this.level++;this.placed=[]}}}this.wallY=270+Math.sin(this.t*(1.4+this.level*.2))*170}
 action(k:string){if(!['tap','action'].includes(k))return;if(this.g.engine==='spikes'){if(this.wallShots.some(y=>Math.abs(y-this.wallY)<29)){this.fail();return}this.wallShots.push(this.wallY);this.score++;this.hits++;if(this.wallShots.length===8){this.wallShots=[];this.level++}}else if(this.projectile===null)this.projectile=500}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,`Nivel ${this.level}`,'Busca un hueco libre');if(this.g.engine==='spikes'){rect(c,320,100,22,370,'#91aa83');for(const y of this.wallShots)line(c,{x:280,y},{x:337,y},C.ink,6);line(c,{x:50,y:this.wallY},{x:110,y:this.wallY},C.green,6);text(c,'→',140,this.wallY,28,C.green)}else{circle(c,210,260,90,'#b8946e');circle(c,210,260,65,'#c9aa84');for(const a of this.placed){const v=a+this.angle;line(c,{x:210+Math.cos(v)*90,y:260+Math.sin(v)*90},{x:210+Math.cos(v)*135,y:260+Math.sin(v)*135},C.ink,6)}line(c,{x:210,y:this.projectile??500},{x:210,y:(this.projectile??500)-45},C.green,7)}text(c,'Toca para disparar',210,525,16,C.muted)}
}
export class Snake extends Engine{
 body:Point[]=[{x:8,y:10},{x:7,y:10},{x:6,y:10}];dir={x:1,y:0};pending={x:1,y:0};food={x:12,y:10};walls:Point[]=[];acc=0;
 step(dt:number){this.acc+=dt;const interval=Math.max(.07,.22-this.score*.008);if(this.acc<interval)return;this.acc-=interval;this.dir=this.pending;const head={x:this.body[0].x+this.dir.x,y:this.body[0].y+this.dir.y};const eat=dist(head,this.food)===0;if(head.x<0||head.x>=18||head.y<0||head.y>=20||this.body.slice(0,eat?undefined:-1).some(b=>dist(b,head)===0)||this.walls.some(b=>dist(b,head)===0)){this.fail();return}this.body.unshift(head);if(eat){this.score++;this.hits++;const free:Point[]=[];for(let x=0;x<18;x++)for(let y=0;y<20;y++)if(!this.body.some(p=>p.x===x&&p.y===y)&&!this.walls.some(p=>p.x===x&&p.y===y))free.push({x,y});if(!free.length){this.finish();return}this.food=free[this.int(0,free.length-1)];if(this.score%4===0){const possible=free.filter(p=>dist(p,head)>5&&dist(p,this.food)>0);if(possible.length)this.walls.push(possible[this.int(0,possible.length-1)])}}else this.body.pop()}
 action(k:string,p:Point){if(k==='tap')k=Math.abs(p.x-210)>Math.abs(p.y-280)?p.x<210?'left':'right':p.y<280?'up':'down';const ds:Record<string,Point>={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}};const d=ds[k];if(d&&(d.x!==-this.dir.x||d.y!==-this.dir.y))this.pending=d;}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Sigue tu apetito','No choques con la cola');rect(c,27,91,366,406,'#dde7d6');for(let i=0;i<18;i++)for(let j=0;j<20;j++)rect(c,30+i*20,94+j*20,18,18,'#eaf0df',3);this.walls.forEach(p=>rect(c,30+p.x*20,94+p.y*20,18,18,C.red,3));this.body.forEach((p,i)=>rect(c,30+p.x*20,94+p.y*20,18,18,i===0?C.ink:C.green,5));circle(c,39+this.food.x*20,103+this.food.y*20,8,C.yellow)}
}
export class Equilibrium extends Engine{
 base=210;angle=.05;omega=0;ball=0;velocity=0;
 step(dt:number){const direction=this.axis('x');const shift=direction*180*dt;this.base=clamp(this.base+shift,55,365);if(this.g.engine==='balance'){this.omega+=(this.angle*2.8-direction*1.9+Math.sin(this.t*2.3)*.08)*dt;this.angle+=this.omega*dt;if(Math.abs(this.angle)>1.1)this.fail();this.score=this.t}else{this.angle=clamp(this.angle+direction*.8*dt,-.5,.5);this.velocity+=(this.angle*140+Math.sin(this.t*2)*5)*dt;this.velocity*=Math.pow(.8,dt);this.ball+=this.velocity*dt;this.score+=dt*(Math.abs(this.ball)<25?2:1);if(Math.abs(this.ball)>145)this.fail()}}
 action(k:string,p:Point){if(['tap','move'].includes(k)&&this.held){if(this.g.engine==='balance'){const dx=p.x-this.base;this.omega-=dx*.002;this.base=clamp(p.x,55,365)}else this.angle=clamp((p.x-210)/340,-.5,.5)}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,this.g.engine==='balance'?'Encuentra el equilibrio':'Mantén la bola centrada','Mueve suavemente a los lados');if(this.g.engine==='balance'){line(c,{x:this.base,y:425},{x:this.base+Math.sin(this.angle)*240,y:425-Math.cos(this.angle)*240},'#7d9586',10);animal(c,this.base,455,C.red,22)}else{const point=(v:number)=>({x:210+Math.cos(this.angle)*v,y:330+Math.sin(this.angle)*v});line(c,point(-160),point(160),'#829b77',12);line(c,point(-25),point(25),C.yellow,14);const p=point(this.ball);circle(c,p.x,p.y-19,17,C.green);text(c,Math.abs(this.ball)<25?'Perfecto · 2×':'',210,170,24,C.green)}}
}
export class Bouncer extends Engine{
 x=210;y=190;vx=80;vy=0;pad=210;segment:{a:Point;b:Point}|null=null;drawStart:Point|null=null;platforms:Point[]=[{x:210,y:490},{x:110,y:390},{x:265,y:285},{x:155,y:175},{x:285,y:65}];combo=0;
 step(dt:number){const en=this.g.engine;this.pad=clamp(this.pad+this.axis('x')*260*dt,45,375);if(en==='jumper')this.vx=this.held?clamp((this.pointer.x-this.x)*3,-190,190):this.axis('x')*190;this.vy+=(en==='flea'?350+this.t*5:450)*dt;this.x+=this.vx*dt;const oldY=this.y;this.y+=this.vy*dt;if(this.x<20||this.x>400){this.x=clamp(this.x,20,400);this.vx=-this.vx}
 if(en==='juggle'&&this.vy>0&&oldY<450&&this.y>=450&&Math.abs(this.x-this.pad)<65){this.vy=-350;this.vx=(this.x-this.pad)*3;this.score++;this.hits++}
 if(en==='flea'&&this.segment&&this.vy>0){const {a,b}=this.segment;const min=Math.min(a.x,b.x),max=Math.max(a.x,b.x);const y=a.y+(b.y-a.y)*(this.x-a.x)/(b.x-a.x||1);if(this.x>=min&&this.x<=max&&oldY<=y&&this.y>=y){this.y=y;this.vy=-350;this.vx=(b.y-a.y)*-1.8;this.combo++;this.score+=this.combo;this.hits++;this.segment=null}}
 if(en==='jumper'){for(const p of this.platforms)if(this.vy>0&&oldY<=p.y&&this.y>=p.y&&Math.abs(this.x-p.x)<50){this.vy=-310;this.hits++}if(this.y<230){const offset=230-this.y;this.y=230;this.platforms.forEach(p=>p.y+=offset);this.score+=offset/8}this.platforms=this.platforms.filter(p=>p.y<600);while(this.platforms.length<5){const top=this.platforms.reduce((a,b)=>a.y<b.y?a:b);this.platforms.push({x:clamp(top.x+this.rand(-95,95),60,360),y:top.y-95})}}
 if(this.y>540)this.fail();
 }
 action(k:string,p:Point){if((k==='tap'||k==='move')&&this.held){if(this.g.engine==='juggle')this.pad=clamp(p.x,45,375);if(this.g.engine==='jumper')this.vx=clamp((p.x-this.x)*3,-190,190)}if(this.g.engine==='flea'){if(k==='tap')this.drawStart=p;if(k==='move'&&this.drawStart)this.segment={a:this.drawStart,b:p};if(k==='release')this.drawStart=null}}
 draw(c:CanvasRenderingContext2D){this.background(c);if(this.g.engine==='juggle'){rect(c,this.pad-55,455,110,20,C.green);animal(c,this.pad,490,C.blue,23)}if(this.g.engine==='flea'){for(let i=0;i<14;i++){c.fillStyle=C.red;c.beginPath();c.moveTo(i*30,560);c.lineTo(i*30+15,530);c.lineTo(i*30+30,560);c.fill()}if(this.segment)line(c,this.segment.a,this.segment.b,C.green,6);text(c,`Combo ×${this.combo}`,210,40,20)}if(this.g.engine==='jumper')this.platforms.forEach(p=>rect(c,p.x-45,p.y,90,12,C.green,6));circle(c,this.x,this.y,14,C.yellow)}
}
export class Timber extends Engine{
 branches:number[]=Array.from({length:8},()=>this.int(0,2));side=0;energy=5;
 step(dt:number){this.energy-=dt;if(this.energy<=0)this.fail()}
 action(k:string,p:Point){if(k==='tap')k=p.x<210?'left':'right';if(!['left','right'].includes(k))return;this.side=k==='left'?0:1;if(this.branches[0]===this.side){this.fail();return}this.branches.shift();this.branches.push(this.int(0,2));this.score++;this.hits++;this.energy=Math.min(5,this.energy+.35)}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Corta y cambia de lado','No te quedes bajo una rama');rect(c,185,95,50,350,'#9db578',4);for(let i=0;i<8;i++){line(c,{x:185,y:125+i*40},{x:235,y:125+i*40},'#6f9358',3);const side=this.branches[7-i];if(side<2)rect(c,side===0?115:235,125+i*40,70,14,C.green,5)}animal(c,this.side===0?130:290,470,C.ink,24);rect(c,55,515,310,10,'#dce4d7');rect(c,55,515,310*clamp(this.energy/5,0,1),10,C.yellow)}
}
export class Slice extends Engine{
 cubes:{x:number;bad:boolean;cut:boolean}[]=[];spawn=0;lives=3;
 step(dt:number){if(this.t>this.spawn){this.spawn=this.t+.65;this.cubes.push({x:450,bad:this.random()<.3,cut:false})}for(const o of this.cubes){o.x-=(130+this.t*2)*dt;if(!o.cut&&o.x<210&&o.x>160&&this.held){o.cut=true;if(o.bad){this.lives--;this.errors++}else{this.score++;this.hits++}}if(!o.cut&&o.x<140){o.cut=true;if(!o.bad){this.lives--;this.errors++}}}this.cubes=this.cubes.filter(o=>o.x>-60);if(this.lives<=0)this.finish('failed');this.message=`${this.lives} vidas`}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Corta los verdes',`${this.lives} vidas · Suelta antes del rojo`);rect(c,0,325,420,12,'#b4c4a9');for(const o of this.cubes)if(!o.cut)rect(c,o.x,250,48,70,o.bad?C.red:C.green,6);line(c,{x:185,y:160},{x:185,y:330},this.held?C.yellow:C.muted,8)}
}
export class Stack extends Engine{
 width=260;center=210;x=65;dir=1;blocks:{x:number;w:number}[]=[];
 step(dt:number){this.x+=this.dir*(125+this.score*8)*dt;if(this.x>420-this.width/2||this.x<this.width/2){this.dir=-this.dir;this.x=clamp(this.x,this.width/2,420-this.width/2)}}
 action(k:string){if(!['tap','action'].includes(k))return;const left=Math.max(this.center-this.width/2,this.x-this.width/2);const right=Math.min(this.center+this.width/2,this.x+this.width/2);if(right<=left){this.fail();return}this.width=right-left;this.center=(right+left)/2;this.blocks.push({x:left,w:this.width});this.score++;this.hits++;this.x=this.width/2;this.dir=1;}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Construye tu torre');const visible=this.blocks.slice(-12);rect(c,80,490,260,25,'#8da27e',4);visible.forEach((b,i)=>rect(c,b.x,465-i*25,b.w,23,i%2?C.green:'#83aa6c',3));rect(c,this.x-this.width/2,440-visible.length*25,this.width,23,C.yellow,3);text(c,'Toca para soltar',210,530,16,C.muted)}
}
export class PathRunner extends Engine{
 nodes:Point[]=[{x:70,y:470},{x:200,y:340},{x:70,y:210},{x:200,y:80},{x:330,y:210},{x:200,y:340}];segment=0;progress=0;turn=false;anchor=false;orbit=0;releaseWindow=false;
 step(dt:number){const en=this.g.engine;const speed=.27+this.score*.003;this.progress+=dt*speed;if(en==='lemur'){if(this.progress>.75&&!this.anchor)this.message='Zona roja · Engánchate';if(this.anchor){this.orbit+=dt*2.8;this.progress=Math.min(this.progress,.85);this.releaseWindow=Math.abs(Math.sin(this.orbit))<.35;this.message=this.releaseWindow?'¡Suelta!':'Mantén…';if(this.orbit>Math.PI*1.8)this.fail()}}if(this.progress>=1){if(!this.turn){this.fail();return}this.progress=0;this.turn=false;this.anchor=false;this.orbit=0;this.segment=(this.segment+1)%(this.nodes.length-1);this.score++;this.hits++}if(this.progress>.93&&!this.turn&&en!=='lemur')this.message='¡Gira!';}
 action(k:string){if(this.g.engine==='lemur'){if(['tap','action'].includes(k)){if(this.progress<.65){this.fail();return}this.anchor=true;this.orbit=.4}if(k==='release'&&this.anchor){if(this.releaseWindow){this.turn=true;this.progress=.99;this.anchor=false}else this.fail()}return}if(['tap','action'].includes(k)){if(this.progress<.7||this.turn){this.fail();return}this.turn=true;this.message='¡Bien!'}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,this.g.engine==='lemur'?'Engancha y suelta':'Gira en cada esquina',this.message);for(let i=1;i<this.nodes.length;i++)line(c,this.nodes[i-1],this.nodes[i],'#c6d7b6',36);const a=this.nodes[this.segment],b=this.nodes[this.segment+1];circle(c,b.x,b.y,21,this.progress>.7?C.red:C.yellow);const p={x:a.x+(b.x-a.x)*this.progress,y:a.y+(b.y-a.y)*this.progress};if(this.anchor){line(c,b,p,C.green,2);circle(c,b.x+Math.cos(this.orbit)*30,b.y+Math.sin(this.orbit)*30,12,C.green)}else animal(c,p.x,p.y,C.green,13)}
}
export class Helix extends Engine{
 rotation=0;depth=0;ring=0;gaps:number[]=Array.from({length:10},()=>this.rand(0,Math.PI*2));
 step(dt:number){this.rotation+=this.axis('x')*2*dt;if(this.keys.has('action')||this.keys.has('down')){const gap=this.gaps[this.ring%10];const diff=Math.abs(Math.atan2(Math.sin(this.rotation-gap),Math.cos(this.rotation-gap)));if(diff<.65){this.depth+=180*dt;if(this.depth>=80){this.depth=0;this.ring++;this.score+=10;this.hits++;this.gaps[(this.ring+9)%10]=this.rand(0,Math.PI*2)}}else if(diff>1.8)this.fail()}this.message='Gira hasta alinear el hueco'}
 action(k:string,p:Point){if(k==='move'&&this.held)this.rotation=(p.x/420)*Math.PI*2;if(k==='left')this.rotation-=.25;if(k==='right')this.rotation+=.25}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Busca el hueco','Gira con ← → · Mantén Descender');for(let i=5;i>=0;i--){const y=160+i*62-this.depth;const gap=this.gaps[(this.ring+i)%10]-this.rotation;c.strokeStyle='#a4b891';c.lineWidth=15;c.beginPath();c.ellipse(210,y,135,30,0,gap+.65,gap+Math.PI*2-.65);c.stroke();c.strokeStyle=C.red;c.beginPath();c.ellipse(210,y,135,30,0,gap+2.1,gap+3.8);c.stroke()}animal(c,210,120,C.green,18)}
}
export class JumperAim extends Engine{
 current={x:100,y:440};target={x:this.rand(200,330),y:300};aim={x:120,y:-140};flying=false;vx=0;vy=0;anchorAngle=0;wait=0;grow=0;angle=-.9;
 step(dt:number){const en=this.g.engine;this.wait+=dt;if(en==='penguin'){this.anchorAngle+=dt*1.5;if(this.wait>6)this.fail()}if(en==='web'){this.angle+=this.axis('x')*dt*1.4;if(this.held){this.grow+=dt*140;if(this.grow>dist(this.current,this.target)+35)this.fail();const tip={x:this.current.x+Math.cos(this.angle)*this.grow,y:this.current.y+Math.sin(this.angle)*this.grow};if(dist(tip,this.target)<25)this.land()}}if(this.flying){this.vy+=420*dt;this.current.x+=this.vx*dt;this.current.y+=this.vy*dt;if(this.vy>0&&Math.abs(this.current.y-this.target.y)<18&&Math.abs(this.current.x-this.target.x)<40)this.land();if(this.current.y>560||this.current.x<0||this.current.x>420)this.fail()}}
 land(){this.score+=this.g.engine==='penguin'?Math.abs(this.current.x-this.target.x)<12?10:5:10;this.hits++;this.current={x:this.target.x,y:440};this.target={x:this.current.x>210?this.rand(70,170):this.rand(250,350),y:300};this.flying=false;this.wait=0;this.grow=0;this.angle=Math.atan2(this.target.y-this.current.y,this.target.x-this.current.x)+.6;this.held=false;this.message='¡Buen salto!'}
 action(k:string,p:Point){const en=this.g.engine;if(en==='web'){if(k==='left')this.angle-=.2;if(k==='right')this.angle+=.2;return}if(en==='penguin'&&['tap','action'].includes(k)){const targetAngle=Math.atan2(this.target.y-this.current.y,this.target.x-this.current.x);const diff=Math.abs(Math.atan2(Math.sin(this.anchorAngle-targetAngle),Math.cos(this.anchorAngle-targetAngle)));if(diff>.55){this.fail();return}this.current={x:this.target.x+(diff>.15?20:0),y:this.target.y};this.land();return}if(en==='frog'){if(k==='move'&&this.held){this.aim={x:clamp(p.x-this.current.x,-220,220),y:-140}}if((k==='release'||k==='action')&&!this.flying){const horizontal=this.aim.x;this.vx=horizontal*1.15;this.vy=-410;this.flying=true}}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,this.g.engine==='web'?'Gira y extiende el hilo':this.g.engine==='penguin'?'Toca cuando apuntes al hielo':'Apunta a la plataforma');rect(c,this.target.x-42,this.target.y+20,84,15,C.green);rect(c,55,460,310,18,'#c5d4b7');if(this.g.engine==='penguin'){line(c,this.current,{x:this.current.x+Math.cos(this.anchorAngle)*90,y:this.current.y+Math.sin(this.anchorAngle)*90},C.ink,3);circle(c,this.current.x,this.current.y,7,C.yellow)}if(this.g.engine==='web')line(c,this.current,{x:this.current.x+Math.cos(this.angle)*Math.max(60,this.grow),y:this.current.y+Math.sin(this.angle)*Math.max(60,this.grow)},C.green,3);if(this.g.engine==='frog'&&!this.flying){for(let i=1;i<10;i++){const t=i*.08;circle(c,this.current.x+this.aim.x*1.15*t,this.current.y-410*t+210*t*t,3,C.green)}}animal(c,this.current.x,this.current.y,C.green,17)}
}
export class Swing extends Engine{
 x=90;y=330;vx=170;vy=0;anchor={x:240,y:110};angle=-1;rope=180;hooked=false;distance=0;columns:{x:number;y:number}[]=[{x:380,y:430}];
 step(dt:number){if(this.hooked){this.angle+=dt*1.4;this.x=this.anchor.x+Math.sin(this.angle)*this.rope;this.y=this.anchor.y+Math.cos(this.angle)*this.rope;this.vx=Math.cos(this.angle)*250;this.vy=-Math.sin(this.angle)*250}else{this.vy+=300*dt;this.x+=this.vx*dt;this.y+=this.vy*dt}if(this.x>200){const delta=this.x-200;this.x=200;this.distance+=delta;this.anchor.x-=delta;this.columns.forEach(p=>p.x-=delta)}if(this.anchor.x<80){this.anchor={x:340,y:100};this.columns.push({x:350,y:440})}this.score=Math.floor(this.distance/10);this.columns=this.columns.filter(p=>p.x>-30);for(const p of this.columns)if(Math.abs(p.x-this.x)<35&&this.y>p.y-10)this.fail();if(this.y>540||this.y<15)this.fail()}
 action(k:string){if(['tap','action'].includes(k)&&dist(this,this.anchor)<300){this.hooked=true;this.rope=dist(this,this.anchor);this.angle=Math.atan2(this.x-this.anchor.x,this.y-this.anchor.y)}if(k==='release')this.hooked=false}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Engancha, balancea y vuela');circle(c,this.anchor.x,this.anchor.y,10,C.yellow);if(this.hooked)line(c,this,this.anchor,C.green,3);for(const p of this.columns)rect(c,p.x-25,p.y,50,H-p.y,'#92ad7d',6);animal(c,this.x,this.y,C.green,18)}
}
export class Moon extends Engine{
 x=70;y=350;vy=0;speed=110;freeze=0;flying=false;
 terrain(x:number){return 350+Math.sin(x/100)*90}
 step(dt:number){const old=this.x;this.speed=clamp(this.speed+(this.held?70:-10)*dt,80,350);this.x+=this.speed*dt;const ground=this.terrain(this.x);if(this.flying){this.vy+=350*dt;this.y+=this.vy*dt;if(this.y>=ground){this.y=ground;this.flying=false}}else this.y=ground;this.score=(this.x-70)/15;if(this.freeze>0){this.freeze-=dt;this.t-=dt}if(this.x-old<0)this.fail()}
 action(k:string){if(k==='release'&&!this.flying){this.flying=true;this.vy=-230;if(Math.cos(this.x/100)<-.6){this.freeze=1;this.message='Perfecto · reloj congelado'}else this.message='¡A volar!'}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Aprovecha las pendientes',this.message||'Mantén para impulsar · Suelta para volar');circle(c,330,110,35,'#e7dba1');c.fillStyle='#a9bf90';c.beginPath();c.moveTo(0,560);for(let x=0;x<=420;x+=5)c.lineTo(x,this.terrain(this.x-110+x)+22);c.lineTo(420,560);c.fill();animal(c,110,this.y,C.ink,19)}
}
