import {Engine,C,clamp,dist,text,rect,circle,line,animal,type Point} from './core';
export class Golf extends Engine{
 ball={x:90,y:440};hole={x:310,y:150};vx=0;vy=0;drag:Point|null=null;aim:Point|null=null;shots=0;obstacles:{x:number;y:number;w:number;h:number}[]=[];
 constructor(...args:ConstructorParameters<typeof Engine>){super(...args);this.field()}
 field(){this.ball={x:80,y:450};this.hole={x:this.rand(230,340),y:this.rand(95,165)};this.vx=0;this.vy=0;this.obstacles=this.g.engine==='golf2'?[{x:160,y:250,w:150,h:25},{x:55,y:330,w:120,h:22}]:[{x:150,y:270,w:100,h:20}]}
 step(dt:number){const old={...this.ball};if(this.g.engine==='golf2'){this.vx+=Math.sin(this.ball.y/100)*12*dt;this.vy+=8*dt}this.ball.x+=this.vx*dt;this.ball.y+=this.vy*dt;const friction=Math.pow(.42,dt);this.vx*=friction;this.vy*=friction;if(this.ball.x<40||this.ball.x>380){this.vx=-this.vx*.8;this.ball.x=clamp(this.ball.x,40,380)}if(this.ball.y<85||this.ball.y>520){this.vy=-this.vy*.8;this.ball.y=clamp(this.ball.y,85,520)}for(const o of this.obstacles)if(this.ball.x>o.x-9&&this.ball.x<o.x+o.w+9&&this.ball.y>o.y-9&&this.ball.y<o.y+o.h+9){if(old.y<=o.y-9||old.y>=o.y+o.h+9)this.vy=-this.vy;else this.vx=-this.vx;this.ball=old}if(dist(this.ball,this.hole)<16&&Math.hypot(this.vx,this.vy)<210){this.hits++;if(this.g.engine==='multigolf'){this.score++;this.field()}else this.finish('completed',this.t)}}
 action(k:string,p:Point){if(k==='tap'&&dist(p,this.ball)<45){this.drag={...this.ball};this.aim=p}if(k==='move'&&this.drag)this.aim=p;if(k==='release'&&this.drag){this.vx=clamp((this.drag.x-p.x)*3.4,-500,500);this.vy=clamp((this.drag.y-p.y)*3.4,-500,500);this.shots++;this.drag=null;this.aim=null;this.message=`${this.shots} golpes`}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Apunta. Suelta. Emboca.',this.g.engine==='golf2'?'Campo con pendientes':'Arrastra hacia atrás desde la bola');rect(c,30,75,360,455,'#d4e6be',20);this.obstacles.forEach(o=>rect(c,o.x,o.y,o.w,o.h,'#899f76',3));circle(c,this.hole.x,this.hole.y,16,C.ink);line(c,this.hole,{x:this.hole.x,y:this.hole.y-48},C.ink,2);rect(c,this.hole.x,this.hole.y-48,25,15,C.yellow,2);if(this.drag&&this.aim)line(c,this.ball,{x:this.ball.x+(this.drag.x-this.aim.x),y:this.ball.y+(this.drag.y-this.aim.y)},C.green,3);circle(c,this.ball.x,this.ball.y,10,'#fff');circle(c,this.ball.x-2,this.ball.y-2,3,'#e1e8da')}
}
export class Maze extends Engine{
 x=70;y=130;vx=0;vy=0;goals:Point[]=[{x:340,y:130},{x:330,y:440},{x:75,y:440}];holes:Point[]=[{x:170,y:200},{x:270,y:310},{x:145,y:395}];drag:Point|null=null;
 step(dt:number){this.vx+=this.axis('x')*230*dt;this.vy+=this.axis('y')*230*dt;this.vx*=Math.pow(.25,dt);this.vy*=Math.pow(.25,dt);this.x=clamp(this.x+this.vx*dt,45,375);this.y=clamp(this.y+this.vy*dt,100,510);if(this.goals.length&&dist(this,this.goals[0])<23){this.goals.shift();this.hits++;if(!this.goals.length)this.finish('completed',this.t)}if(this.holes.some(p=>dist(this,p)<18))this.fail()}
 action(k:string,p:Point){if(k==='tap')this.drag=p;if(k==='move'&&this.drag){this.vx=clamp((p.x-this.drag.x)*3,-160,160);this.vy=clamp((p.y-this.drag.y)*3,-160,160)}if(k==='release')this.drag=null}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Visita las tres metas','Evita los agujeros oscuros');rect(c,30,85,360,440,'#e1cfac',14);this.holes.forEach(p=>circle(c,p.x,p.y,21,'#706b55'));this.goals.forEach((p,i)=>{circle(c,p.x,p.y,24,i===0?C.green:C.mint);text(c,String(i+1),p.x,p.y,18,i===0?'#fff':C.green)});circle(c,this.x,this.y,13,'#fafbf0')}
}
export class Race extends Engine{
 x=345;y=300;vx=0;vy=0;angle=Math.PI/2;checkpoint=1;lap=0;round=0;roundStart=0;times:number[]=[];progress=0;speed=0;danger=0;drag:Point|null=null;
 point(a:number){return {x:210+Math.cos(a)*135,y:300+Math.sin(a)*185}}
 step(dt:number){const en=this.g.engine;
 if(en==='slot'){this.speed=clamp(this.speed+(this.keys.has('up')||this.held?1.1:-.25)*dt-(this.keys.has('down')?2.5*dt:0),.08,1.6);const bend=Math.abs(Math.cos(this.progress));this.danger=clamp(this.danger+((bend>.7&&this.speed>1)?.9:-1.2)*dt,0,1);if(this.danger===1){this.progress=Math.floor(this.progress/(Math.PI/2))*(Math.PI/2);this.speed=.2;this.danger=0;this.errors++;this.message='Salida · reduce en las curvas'}this.progress+=this.speed*dt;const p=this.point(this.progress);this.x=p.x;this.y=p.y;if(this.progress>=Math.PI*6)this.finish('completed',this.t);this.lap=Math.floor(this.progress/(Math.PI*2));return}
 if(en==='ballrace'){this.vx+=this.axis('x')*260*dt;this.vy+=this.axis('y')*260*dt;this.vx*=Math.pow(.2,dt);this.vy*=Math.pow(.2,dt)}else{this.angle+=this.axis('x')*2.5*dt;const auto=en==='roadrace';this.speed=clamp(this.speed+((auto||this.keys.has('up')||this.held)?130:-50)*dt-(this.keys.has('down')?220*dt:0),0,210);this.vx=Math.cos(this.angle)*this.speed;this.vy=Math.sin(this.angle)*this.speed}
 const old={x:this.x,y:this.y};this.x+=this.vx*dt;this.y+=this.vy*dt;const norm=Math.hypot((this.x-210)/135,(this.y-300)/185);if(norm<.72||norm>1.25){this.x=old.x;this.y=old.y;this.speed*=.6;this.vx*=.4;this.vy*=.4}
 const target=this.point(this.checkpoint*Math.PI/2);if(dist(this,target)<43){this.checkpoint++;this.hits++;if(this.checkpoint%4===1){this.lap++;if(this.lap>=(en==='ballrace'?1:2)){if(en==='ballrace'){this.times.push(this.t-this.roundStart);this.round++;if(this.round===2)this.finish('completed',Math.min(...this.times));else{this.roundStart=this.t;this.x=345;this.y=300;this.vx=0;this.vy=0;this.checkpoint=1;this.lap=0}}else this.finish('completed',this.t)}}}this.score=this.t;
 }
 action(k:string,p:Point){if(k==='tap')this.drag=p;if(k==='move'&&this.drag){if(this.g.engine==='ballrace'){this.vx=clamp((p.x-this.drag.x)*3,-180,180);this.vy=clamp((p.y-this.drag.y)*3,-180,180)}else this.angle=Math.atan2(p.y-this.y,p.x-this.x)}if(k==='release')this.drag=null}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,this.g.engine==='ballrace'?`Ronda ${this.round+1} de 2`:`Vuelta ${Math.min(this.lap+1,this.g.engine==='slot'?3:2)}`,this.g.engine==='slot'?'Gas en rectas, freno en curvas':'Sigue los puntos de control');c.strokeStyle='#c8d3bb';c.lineWidth=70;c.beginPath();c.ellipse(210,300,135,185,0,0,Math.PI*2);c.stroke();c.strokeStyle='#f7f8ec';c.lineWidth=2;c.setLineDash([10,10]);c.stroke();c.setLineDash([]);if(this.g.engine!=='slot'){const p=this.point(this.checkpoint*Math.PI/2);circle(c,p.x,p.y,18,C.yellow);text(c,'↓',p.x,p.y,18)}animal(c,this.x,this.y,C.green,15);if(this.g.engine==='slot'){rect(c,60,525,300,10,'#dce4d7');rect(c,60,525,300*this.danger,10,C.red)}text(c,this.message,210,545,12,C.red)}
}
