import {Engine,C,W,H,clamp,dist,text,rect,circle,line,animal,button,type Point} from './core';
export class Targets extends Engine{
 targets:{x:number;y:number;expire:number;id:number}[]=[];spawn=0;lives=3;energy=6;count=0;
 step(dt:number){const switches=this.g.engine==='switches';if(switches){this.energy-=dt;if(this.energy<=0)this.finish('failed')}if(this.t>=this.spawn){this.spawn=this.t+Math.max(.3,.95-this.score*.015);const slots=Array.from({length:12},(_,i)=>({x:70+i%4*93,y:150+Math.floor(i/4)*120})).filter(p=>!this.targets.some(t=>dist(t,p)<50));if(slots.length){const p=slots[this.int(0,slots.length-1)];this.targets.push({...p,expire:this.t+Math.max(.8,2.5-this.score*.015),id:this.count++})}}for(const o of [...this.targets])if(o.expire<this.t){this.targets=this.targets.filter(t=>t!==o);this.errors++;if(!switches){this.lives--;if(this.lives<=0)this.finish('failed')}}this.message=switches?`${this.energy.toFixed(1)} s restantes`:`${this.lives} vidas`}
 action(k:string,p:Point){if(k==='action')p=this.targets[0]??p;if(!['tap','action'].includes(k))return;const o=this.targets.find(o=>dist(o,p)<33);if(o){this.targets=this.targets.filter(t=>t!==o);this.score++;this.hits++;this.energy=Math.min(8,this.energy+1)}else if(this.g.engine==='targets'){this.errors++;this.lives--;if(this.lives<=0)this.finish('failed')}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,this.g.engine==='switches'?'Enciéndelos a tiempo':'¡Atrápalos!',this.message);for(const o of this.targets){circle(c,o.x,o.y,33,C.mint);circle(c,o.x,o.y,22,this.g.engine==='switches'?C.yellow:C.green);const remaining=clamp((o.expire-this.t)/2.5,0,1);c.strokeStyle=C.green;c.lineWidth=4;c.beginPath();c.arc(o.x,o.y,37,-Math.PI/2,-Math.PI/2+remaining*Math.PI*2);c.stroke()}if(this.g.engine==='switches'){rect(c,55,510,310,10,'#dce4d7');rect(c,55,510,310*clamp(this.energy/8,0,1),10,C.yellow)}}
}
export class Tap extends Engine{
 pulse=0;step(dt:number){this.pulse=Math.max(0,this.pulse-dt)}
 action(k:string){if(['tap','action'].includes(k)){this.score++;this.hits++;this.pulse=.15}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'¡Dale al tronco!','Cada toque cuenta');rect(c,150,170,120,310,'#b88d62',35);for(let i=0;i<8;i++)line(c,{x:168+i*12,y:180},{x:163+i*12,y:450},'#a67a51',2);animal(c,210,300,this.pulse?C.yellow:C.green,this.pulse?45:40);text(c,String(this.score),210,115,40);text(c,'Toca o pulsa Espacio',210,520,18,C.muted)}
}
export class Piano extends Engine{
 notes:{lane:number;y:number}[]=[];spawn=0;
 step(dt:number){if(this.t>this.spawn){this.spawn=this.t+Math.max(.2,.7-this.score*.007);this.notes.push({lane:this.int(0,3),y:80})}for(const n of this.notes){n.y+=(125+this.score*2.5)*dt;if(n.y>530)this.fail()}}
 action(k:string,p:Point){let lane=['a','s','d','f'].indexOf(k);if(k==='tap')lane=Math.floor(p.x/105);if(lane<0||lane>3)return;const n=[...this.notes].filter(n=>n.lane===lane).sort((a,b)=>b.y-a.y)[0];if(n&&(k!=='tap'||Math.abs(p.y-n.y)<65)){this.notes=this.notes.filter(o=>o!==n);this.score++;this.hits++}else this.fail()}
 draw(c:CanvasRenderingContext2D){this.background(c);for(let i=0;i<4;i++){rect(c,i*105+3,85,99,455,i%2?'#e2e8da':'#edf0e5',4);text(c,['A','S','D','F'][i],i*105+52,520,20,C.muted)}for(const n of this.notes)rect(c,n.lane*105+8,n.y-30,89,60,C.green,7);this.header(c,'Toca las teclas verdes')}
}
export class Conveyor extends Engine{
 items:{x:number;kind:number;used:boolean}[]=[];spawn=0;colors=[C.green,C.yellow,C.purple];
 step(dt:number){if(this.t>this.spawn){this.spawn=this.t+Math.max(.55,1.35-this.score*.006);this.items.push({x:450,kind:this.int(0,this.g.engine==='stamp'?1:2),used:false})}for(const o of this.items){o.x-=(100+this.score*.6)*dt;if(o.x<40&&!o.used){o.used=true;this.errors++}}this.items=this.items.filter(o=>o.x>-70)}
 action(k:string){if(this.g.engine==='stamp'){if(!['tap','action'].includes(k))return;const o=this.items.find(o=>!o.used&&Math.abs(o.x-210)<48);if(!o)return;o.used=true;if(o.kind===1){this.score=Math.max(0,this.score-1);this.errors++}else{this.score+=Math.abs(o.x-210)<14?2:1;this.hits++}}else{const map:Record<string,number>={left:0,up:1,right:2};if(!(k in map))return;const o=this.items.filter(o=>!o.used).sort((a,b)=>a.x-b.x)[0];if(!o)return;o.used=true;if(o.kind===map[k]){this.score++;this.hits++}else this.errors++}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,this.g.engine==='stamp'?'Sella solo las cartas verdes':'Cada paquete a su color');rect(c,0,275,420,75,'#d6ddcf');for(let x=0;x<420;x+=35)circle(c,x,345,9,'#a4b39a');for(const o of this.items)if(!o.used){rect(c,o.x-25,285,50,48,this.g.engine==='stamp'?(o.kind?C.red:C.green):this.colors[o.kind],6);if(this.g.engine==='stamp')text(c,o.kind?'×':'✓',o.x,309,20,'#fff')}if(this.g.engine==='stamp'){rect(c,180,170,60,110,'#97aa89');text(c,'↓',210,250,30,'#fff');text(c,'Toca cuando pase debajo',210,430,18,C.muted)}else this.colors.forEach((color,i)=>{rect(c,45+i*120,410,90,80,color);text(c,['←','↑','→'][i],90+i*120,450,28,i===1?C.ink:'#fff')})}
}
export class Bingo extends Engine{
 card:number[]=this.shuffled(Array.from({length:20},(_,i)=>i+1)).slice(0,4);drawn=new Set<number>();marked=new Set<number>();current=0;next=0;lives=3;
 step(_dt:number){if(this.t>=this.next){this.next=this.t+1.1;this.current=this.int(1,20);this.drawn.add(this.current)}}
 action(k:string,p:Point){if(k!=='tap')return;const col=Math.floor((p.x-75)/140),row=Math.floor((p.y-225)/120);if(col<0||col>1||row<0||row>1)return;const i=row*2+col;if(this.marked.has(i))return;if(this.drawn.has(this.card[i])){this.marked.add(i);this.score+=5;this.hits++;if(this.marked.size===4){this.score+=10;this.card=this.shuffled(Array.from({length:20},(_,i)=>i+1)).slice(0,4);this.drawn.clear();this.marked.clear()}}else{this.errors++;this.lives--;if(this.lives<=0)this.finish('failed')}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Marca los números que salgan',`${this.lives} vidas`);circle(c,210,140,46,C.yellow);text(c,String(this.current||'…'),210,140,32);this.card.forEach((v,i)=>{rect(c,75+i%2*140,225+Math.floor(i/2)*120,125,105,this.marked.has(i)?C.green:'#fff');text(c,String(v),137+i%2*140,278+Math.floor(i/2)*120,34,this.marked.has(i)?'#fff':C.ink)});text(c,`Han salido: ${[...this.drawn].slice(-10).join(' · ')}`,210,505,13,C.muted)}
}
export class Arrows extends Engine{
 slots=Array.from({length:4},()=>({dir:this.int(0,3),expire:this.t+this.rand(3,5)}));
 step(_dt:number){for(let i=0;i<4;i++)if(this.slots[i].expire<this.t){this.errors++;this.slots[i]={dir:this.int(0,3),expire:this.t+this.rand(2,4)}}}
 action(k:string){const dir=['left','up','right','down'].indexOf(k);if(dir<0)return;const candidates=this.slots.map((s,i)=>({...s,i})).filter(s=>s.dir===dir).sort((a,b)=>a.expire-b.expire);if(candidates.length){this.score++;this.hits++;this.slots[candidates[0].i]={dir:this.int(0,3),expire:this.t+this.rand(2,4)}}else this.errors++}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Desliza en la dirección indicada','Atiéndelas antes de que se vacíen');this.slots.forEach((s,i)=>{const x=60+i%2*160,y=160+Math.floor(i/2)*170;rect(c,x,y,140,140,'#e0e9d8');text(c,['←','↑','→','↓'][s.dir],x+70,y+62,45,C.green);rect(c,x+15,y+110,110,8,'#c3d2b9');rect(c,x+15,y+110,110*clamp((s.expire-this.t)/4,0,1),8,C.yellow)})}
}
export class Basket extends Engine{
 angle=0;remaining=10;active=false;flight=0;shotAngle=0;scored=false;
 step(dt:number){this.angle=Math.sin(this.t*(2+this.score*.12))*.8;if(this.active)this.remaining-=dt;if(this.remaining<=0)this.finish();if(this.flight>0){this.flight+=dt;if(this.flight>1){this.flight=0;const error=Math.abs(this.shotAngle-.4);if(error<.19){this.score++;this.hits++;this.remaining+=this.active?2:0;this.active=true;this.message='¡Canasta!'}else{this.errors++;this.message='Prueba otro ángulo'}}}}
 action(k:string){if(['tap','action'].includes(k)&&this.flight===0){this.shotAngle=this.angle;this.flight=.001}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Apunta al aro',this.active?`${this.remaining.toFixed(1)} s restantes`:'La primera canasta inicia el reloj');rect(c,325,160,10,200,'#a9b5a0');line(c,{x:280,y:240},{x:335,y:240},C.red,6);if(this.flight>0){const t=this.flight;circle(c,110+Math.cos(this.shotAngle)*220*t,445-480*t+275*t*t,13,C.yellow)}else circle(c,110,445,13,C.yellow);line(c,{x:110,y:445},{x:110+Math.cos(this.angle)*90,y:445-90+Math.sin(this.angle)*70},C.green,3);text(c,this.message,210,510,20,C.green)}
}
export class Thrower extends Engine{
 ball={x:90,y:450};vx=0;vy=0;flight=false;drag:Point|null=null;aim:Point|null=null;target={x:300,y:200};wind=this.rand(-35,35);
 step(dt:number){if(this.flight){this.vx+=this.wind*dt;this.vy+=280*dt;this.ball.x+=this.vx*dt;this.ball.y+=this.vy*dt;if(dist(this.ball,this.target)<30){this.score+=100;this.hits++;this.reset()}else if(this.ball.y>560||this.ball.x<0||this.ball.x>420){this.errors++;this.reset()}}}
 reset(){this.ball={x:90,y:450};this.flight=false;this.target={x:this.rand(210,350),y:this.rand(160,320)};this.wind=this.rand(-35,35)}
 action(k:string,p:Point){if(k==='tap'&&!this.flight&&dist(p,this.ball)<45){this.drag=p;this.aim=p}if(k==='move'&&this.drag)this.aim=p;if(k==='release'&&this.drag){this.vx=clamp((this.drag.x-p.x)*3,-400,400);this.vy=clamp((this.drag.y-p.y)*3,-450,200);this.flight=true;this.drag=null;this.aim=null}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Lanza al flotador',`Viento ${this.wind<0?'←':'→'} ${Math.abs(this.wind).toFixed(0)}`);rect(c,0,360,W,200,'#d9eaf0',0);circle(c,this.target.x,this.target.y,30,C.red);circle(c,this.target.x,this.target.y,17,C.paper);rect(c,35,465,120,25,'#b79c77');circle(c,this.ball.x,this.ball.y,12,C.yellow);if(this.drag&&this.aim)line(c,this.ball,{x:this.ball.x+this.drag.x-this.aim.x,y:this.ball.y+this.drag.y-this.aim.y},C.green,3)}
}
export class Garden extends Engine{
 angle=0;flies:{x:number;y:number;color:number}[]=[];spawn=0;colors=[C.yellow,C.purple,C.red];
 step(dt:number){this.angle=clamp(this.angle+this.axis('x')*1.4*dt,-1,1);if(this.t>this.spawn){this.spawn=this.t+1;this.flies.push({x:this.rand(80,340),y:80,color:this.int(0,2)})}for(const f of this.flies){f.y+=75*dt;const beam=210+Math.sin(this.angle)*(f.y-50);if(Math.abs(f.x-beam)<60)f.x+=Math.sin(this.angle)*120*dt;if(f.y>465){const bin=Math.round((f.x-90)/120);if(bin===f.color){this.score++;this.hits++}else this.errors++;f.y=600}}this.flies=this.flies.filter(f=>f.y<560)}
 action(k:string,p:Point){if(['tap','move'].includes(k)&&this.held)this.angle=clamp((p.x-210)/180,-1,1)}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,'Guíalas hacia su flor','Gira el haz de luz');c.fillStyle='#f5e9a9';c.beginPath();c.moveTo(210,80);c.lineTo(210+Math.sin(this.angle)*420-55,500);c.lineTo(210+Math.sin(this.angle)*420+55,500);c.fill();circle(c,210,80,23,'#e8d893');this.colors.forEach((color,i)=>{for(let j=0;j<5;j++){const a=j*Math.PI*2/5;circle(c,90+i*120+Math.cos(a)*15,490+Math.sin(a)*15,12,color)}circle(c,90+i*120,490,9,C.yellow)});this.flies.forEach(f=>{circle(c,f.x,f.y,10,this.colors[f.color]);circle(c,f.x-8,f.y-7,6,'#e8eedd');circle(c,f.x+8,f.y-7,6,'#e8eedd')})}
}
export class Bricks extends Engine{
 bricks:{x:number;y:number;hp:number}[]=[];balls:{x:number;y:number;vx:number;vy:number}[]=[];origin={x:210,y:520};aim:Point|null=null;drag:Point|null=null;round=1;remaining=0;spawn=0;
 constructor(...args:ConstructorParameters<typeof Engine>){super(...args);this.addRow()}
 addRow(){this.bricks.forEach(b=>b.y+=52);if(this.bricks.some(b=>b.y>460)){this.fail();return}for(let i=0;i<6;i++)if(this.random()>.28)this.bricks.push({x:25+i*63,y:110,hp:this.round})}
 step(dt:number){if(this.remaining>0&&this.t>this.spawn){this.spawn=this.t+.08;this.remaining--;const p=this.aim!;const a=Math.atan2(p.y-this.origin.y,p.x-this.origin.x);this.balls.push({...this.origin,vx:Math.cos(a)*350,vy:Math.min(-70,Math.sin(a)*350)})}for(const b of this.balls){const old={x:b.x,y:b.y};b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<10||b.x>410){b.vx=-b.vx;b.x=clamp(b.x,10,410)}if(b.y<85){b.vy=Math.abs(b.vy);b.y=85}for(const brick of this.bricks)if(brick.hp>0&&b.x>brick.x-7&&b.x<brick.x+53&&b.y>brick.y-7&&b.y<brick.y+45){brick.hp--;if(old.y<brick.y-7||old.y>brick.y+45)b.vy=-b.vy;else b.vx=-b.vx;this.score++;this.hits++;break}}const was=this.balls.length>0;this.balls=this.balls.filter(b=>b.y<540);this.bricks=this.bricks.filter(b=>b.hp>0);if(was&&this.balls.length===0&&this.remaining===0){this.round++;this.addRow();this.aim=null}}
 action(k:string,p:Point){if(this.balls.length||this.remaining)return;if(k==='tap'){this.drag=p;this.aim={x:p.x,y:Math.min(p.y,440)}}if(k==='move'&&this.drag)this.aim={x:p.x,y:Math.min(p.y,440)};if(k==='release'&&this.drag){this.drag=null;this.remaining=Math.min(15,2+this.round);this.spawn=this.t}}
 draw(c:CanvasRenderingContext2D){this.background(c);this.header(c,`Ronda ${this.round}`,'Apunta hacia arriba y suelta');for(const b of this.bricks){rect(c,b.x,b.y,50,40,b.hp>3?C.red:C.green,5);text(c,String(b.hp),b.x+25,b.y+20,20,'#fff')}for(const b of this.balls)circle(c,b.x,b.y,6,C.yellow);circle(c,this.origin.x,this.origin.y,8,C.green);if(this.aim&&this.drag)line(c,this.origin,this.aim,C.green,2);line(c,{x:10,y:480},{x:410,y:480},C.red,2)}
}
