import { useEffect,useRef,useState } from 'react';
import Phaser from 'phaser';
import { ArrowLeft,ArrowRight,ArrowUp,ArrowDown,Pause,Play,X } from 'lucide-react';
import { createEngine } from './games';
import { Engine, W,H,text,rect,C,type End } from './games/core';
import { formatScore,type GameDef } from './catalog';
import type { Result,Settings } from './model';
export default function GameStage({g,run,settings,onFinish}:{g:GameDef;run:Result;settings:Settings;onFinish:(end:End,duration:number)=>void}){
 const host=useRef<HTMLDivElement>(null);const engine=useRef<Engine|null>(null);const [hud,setHud]=useState({score:0,time:0,message:''});const [paused,setPaused]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState('');const pauseRef=useRef(false);const finished=useRef(false);const started=useRef(false);
 const end=(status:End['status'])=>{const e=engine.current;if(e&&!finished.current){e.finish(status);finished.current=true;onFinish(e.done!,e.elapsed)}};
 useEffect(()=>{let disposed=false;let lastHud=0;let remaining=3;let last=performance.now();let game:Phaser.Game|undefined;let audio:AudioContext|undefined;let lastHits=0;
 const e=createEngine(g,run.seed);engine.current=e;
 const beep=()=>{if(!settings.sound)return;try{audio??=new AudioContext();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);osc.frequency.value=520;osc.start();osc.stop(audio.currentTime+.13)}catch{/* sound may be blocked until a gesture */}};
 class Scene extends Phaser.Scene{texture!:Phaser.Textures.CanvasTexture;create(){this.texture=this.textures.createCanvas('board',W,H)!;this.add.image(0,0,'board').setOrigin(0);this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(remaining<=0&&!pauseRef.current&&!finished.current){if(['arrows','snake','crossing','traffic'].includes(g.engine)){e.held=true;e.pointer={x:p.x,y:p.y}}else e.input('down',{x:p.x,y:p.y})}});this.input.on('pointermove',(p:Phaser.Input.Pointer)=>{if(p.isDown&&remaining<=0&&!pauseRef.current&&!finished.current)e.input('move',{x:p.x,y:p.y})});this.input.on('pointerup',(p:Phaser.Input.Pointer)=>{if(remaining<=0&&!pauseRef.current&&!finished.current){const start=p.downX!==undefined?{x:p.downX,y:p.downY}:{x:p.x,y:p.y};if(['arrows','snake','crossing','traffic'].includes(g.engine)&&Math.hypot(p.x-start.x,p.y-start.y)>30){const dx=p.x-start.x,dy=p.y-start.y;e.action(Math.abs(dx)>Math.abs(dy)?dx<0?'left':'right':dy<0?'up':'down',{x:p.x,y:p.y})}else if(['arrows','snake','crossing','traffic'].includes(g.engine))e.action('tap',{x:p.x,y:p.y});e.input('up',{x:p.x,y:p.y})}});setReady(true)}
 update(){if(disposed)return;const now=performance.now();const dt=Math.max(0,(now-last)/1000);last=now;if(!pauseRef.current&&!finished.current){if(remaining>0){remaining-=Math.min(dt,.1)}else if(!e.done){started.current=true;if(dt>2&&run.mode==='daily')e.finish('abandoned');else{let advance=Math.min(dt,2);while(advance>0&&!e.done){const step=Math.min(advance,1/120);e.tick(step);advance-=step}}}if(e.done&&!finished.current){finished.current=true;onFinish(e.done,e.elapsed)}}
 const c=this.texture.context;e.draw(c);if(remaining>0){rect(c,0,0,W,H,'#f5f6e9dd',0);text(c,String(Math.max(1,Math.ceil(remaining))),210,245,85,C.green);text(c,'Prepárate…',210,330,20,C.muted)}if(e.hits>lastHits){beep();lastHits=e.hits}this.texture.refresh();if(now-lastHud>100){setHud(e.hud());lastHud=now}}
 }
 try{game=new Phaser.Game({type:Phaser.CANVAS,parent:host.current!,width:W,height:H,backgroundColor:C.paper,scene:Scene,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true},audio:{noAudio:true},banner:false})}catch(err){setError(err instanceof Error?err.message:'No se pudo iniciar el juego')}
 const map:Record<string,string>={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',w:'up',s:g.engine==='piano'?'s':'down',a:g.engine==='piano'?'a':'left',d:g.engine==='piano'?'d':'right',' ':'action',Enter:'enter',Backspace:'back'};
 const key=(event:KeyboardEvent,down:boolean)=>{const mapped=map[event.key]??event.key.toLowerCase();if(!['left','right','up','down','action','enter','back','a','s','d','f','0','1','2','3','4','5','6','7','8','9'].includes(mapped))return;if(['INPUT','TEXTAREA','SELECT'].includes((event.target as HTMLElement).tagName))return;event.preventDefault();if(down&&event.repeat)return;if(remaining<=0&&!pauseRef.current&&!finished.current)e.key(mapped,down)};const kd=(event:KeyboardEvent)=>key(event,true),ku=(event:KeyboardEvent)=>key(event,false);window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);
 const hidden=()=>{if(!document.hidden)return;e.held=false;e.keys.clear();if(run.mode==='daily'){e.finish('abandoned');if(!finished.current){finished.current=true;onFinish(e.done!,e.elapsed)}}else{pauseRef.current=true;setPaused(true)}};document.addEventListener('visibilitychange',hidden);
 return ()=>{disposed=true;window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);document.removeEventListener('visibilitychange',hidden);game?.destroy(true);void audio?.close();engine.current=null};
 // A run is immutable; remount for a new attempt.
 },[run.id]);
 function control(k:string,down:boolean){if(!ready||!started.current||pauseRef.current||finished.current)return;engine.current?.key(k,down)}
 function pad(k:string,label:string,icon:React.ReactNode){return <button aria-label={label} className="pad" onPointerDown={ev=>{ev.preventDefault();ev.currentTarget.setPointerCapture(ev.pointerId);control(k,true)}} onPointerUp={()=>control(k,false)} onPointerCancel={()=>control(k,false)}>{icon}</button>}
 function togglePause(){if(run.mode==='daily')return;pauseRef.current=!pauseRef.current;engine.current?.keys.clear();if(engine.current)engine.current.held=false;setPaused(pauseRef.current)}
 return <div className="play-screen" role="dialog" aria-modal="true" aria-label={g.name}>
 <div className="play-toolbar"><div><span className="eyebrow">{run.mode==='daily'?'RETO DIARIO':'ENTRENAMIENTO'}</span><h2>{g.name}</h2></div><div className="toolbar-actions">{run.mode==='training'&&<button className="icon-button" aria-label="Pausar" onClick={togglePause}><Pause size={20}/></button>}<button className="icon-button" aria-label="Abandonar partida" onClick={()=>end('abandoned')}><X size={22}/></button></div></div>
 <div className="game-hud"><span><small>MARCADOR</small><b>{formatScore(g,hud.score)}</b></span><span><small>{g.limit?'TIEMPO RESTANTE':'TIEMPO'}</small><b>{hud.time.toFixed(1)} s</b></span></div>
 <div className="game-board" ref={host}>{!ready&&!error&&<p className="loading">Preparando el juego…</p>}{error&&<p role="alert">{error}</p>}{paused&&<div className="pause-overlay"><Pause size={32}/><h3>Un respiro</h3><p>Tu entrenamiento está en pausa.</p><button className="primary" onClick={togglePause}><Play size={16}/> Continuar</button></div>}</div>
 <div className="game-controls">{pad('left','Izquierda',<ArrowLeft/>)}<div className="vertical-pad">{pad('up','Arriba / Gas',<ArrowUp/>)}{pad('down','Abajo / Freno',<ArrowDown/>)}</div>{pad('right','Derecha',<ArrowRight/>)}{pad('action',g.engine==='helix'?'Descender':g.engine==='web'?'Crecer':'Acción',<span>{g.engine==='helix'?'Bajar':g.engine==='web'?'Crecer':'●'}</span>)}</div><p className="controls-hint">{g.controls}</p>{hud.message&&<p className="game-message">{hud.message}</p>}
 </div>
}
